### ISSUE TITLE
Student Academic Analytics - Version 1 and 2 methods are not accessible when a Security Role has been defined

### ISSUE THREAD

**Issue by puffyliondog** [TheAlphaSchoolSystemPTYLTD/student-academic-analytics#17]
I consistently get the following response: 

{"__status":"invalid","__msg":"Version 1 and 2 methods are not accessible when a Security Role has been defined.","__invalid":{}}

I asked the my ICT manager to check all the possible combinations of credentials to try and replicate a version 2 API without a Security Role to no avail. 

Can anyone confirm that this API is actually working?

**Comment by tassweb-talon** [comment]
hi there,

Security Roles are defined in System Admin > Utilities > API Gateway Maintenance on the 'TASS APIs' tab.

Please contact your ICT manager and set the Security Roles to empty for Student Academic Analytics.

For more info visit:
https://hub.tassweb.com.au/confluence/help-centre/documentation/latest/how-to-checklists/how-integrations/tass-api-setup-checklist

or contact our customer support team.

thanks.
