### ISSUE TITLE
What Permissions are required for each Method?

### ISSUE THREAD

**Issue by brettm-pmsa** [TheAlphaSchoolSystemPTYLTD/student-academic-analytics#20]
Hi Guys,

Just looking at using the student-academic-analytics API to do some custom reporting, but the methods don't have what permissions are required.  Most of the other API's Methods have a bullet point for "Permissions" that details what permission is required for each method - can you please add this to the student-academic-analytics methods?

Would appreciate this being done fairly quickly as we are keen to leverage this API but cannot work out what permissions we need to assign.

Thanks!

**Comment by scottetass** [comment]
Hi,

Student academic analytics is a version 2 API and it doesn't require a security role to be assigned.

If you have a security role already assigned against the API setup, then you will need to remove it and you should be good to go.

![image](https://github.com/TheAlphaSchoolSystemPTYLTD/student-academic-analytics/assets/149555853/173dcdc3-587c-4118-ac9d-b06018bd689f)

Thanks, Scott

**Comment by brettm-pmsa** [comment]
Ah, right - that may be our issue - I'll have the IT Teams check.

Thanks!
Brett.
